// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhD__gCe74bpCt9aH4muEhXzybAgku59Q',
    appId: '1:841658932681:web:9c4bdca342999351e89c18',
    messagingSenderId: '841658932681',
    projectId: 'crudfirebase-71987',
    authDomain: 'crudfirebase-71987.firebaseapp.com',
    databaseURL: 'https://crudfirebase-71987-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crudfirebase-71987.appspot.com',
    measurementId: 'G-68KZ7JQ092',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvjNhac86fYoFKkBkHExRd2SK66vnXZcI',
    appId: '1:841658932681:android:5a63c35501a1bc59e89c18',
    messagingSenderId: '841658932681',
    projectId: 'crudfirebase-71987',
    databaseURL: 'https://crudfirebase-71987-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crudfirebase-71987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANNzSrHP9wANPaBEBStKy7RYB9txeNq2o',
    appId: '1:841658932681:ios:431e26bd48c1d53ee89c18',
    messagingSenderId: '841658932681',
    projectId: 'crudfirebase-71987',
    databaseURL: 'https://crudfirebase-71987-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crudfirebase-71987.appspot.com',
    iosClientId: '841658932681-fkgi1q781lm638nt205djrjiqgqgu4hl.apps.googleusercontent.com',
    iosBundleId: 'com.pahnal.presence',
  );
}
